### ISSUE TITLE
replace deprecated qtwebkit with qtwebengine

### ISSUE THREAD

**Issue by t0b3** [opengisch/qgis-swiss-locator#11]
https://github.com/opengisch/qgis-swiss-locator/blob/3c6dfc560ce5312d1b4bb12510a57bea7d797717/swiss_locator/gui/maptip.py#L25-L26

**Comment by t0b3** [comment]
depends on https://github.com/qgis/QGIS/issues/26048

**Comment by 3nids** [comment]
as long as QGIS uses QtWebkit, there is not much we can do.
