### ISSUE TITLE
lxml not by default on windows

### ISSUE THREAD

**Issue by 3nids** [opengisch/qgis-swiss-locator#17]
Some windows users are reporting that lxml is missing.
Any chance to use the system ElementTree: https://docs.python.org/3/library/xml.etree.elementtree.html

They seem to be compatible: https://lxml.de/1.3/compatibility.html

ping @danjov this was added in #13

**Comment by 3nids** [comment]
![image](https://user-images.githubusercontent.com/127259/115716194-388bfa00-a379-11eb-9707-422d04768cfb.png)

**Comment by danjov** [comment]
@3nids Thanks for reporting. We'll take a look into it and replace [lxml](https://lxml.de/) with [ElementTree](https://docs.python.org/3/library/xml.etree.elementtree.html).

**Comment by 3nids** [comment]
Thanks!
