### ISSUE TITLE
Adress localisation not working

### ISSUE THREAD

**Issue by varrieta** [opengisch/qgis-swiss-locator#18]
When fetching adresses, the localisator get lost and moves me to coordinates (0,0).

I have tried with projects in EPSG 2056 and 21781, the problem is the same. 

It does work well for municipal boundaries or for loading WMS layers.

**Comment by skitourenguru** [comment]
I have the same Problem:
- Well known administrative names seem to work: 'Alvaneu'
- Minor place names return the coordinate (0,0): 'Bifertenstock'
Would be a wonderful feature, if only it did work...

**Comment by FrauMahlzahn** [comment]
I have a similar Problem: 

- Project EPSG 2056
- Layer EPSG 2056

When I search for an Address, eg. Beundenfeldstrasse 11, in the Locator Search Bar, I get several hits. 

-  The search results from "Swiss Geoportal Featuers >  Gebäude- und Wohnungsregister work fine, I get to the right place
-  Search results from "Swiss Geoportal Locations" > "Index" work fine as well
- Search results from "Swiss Geoportal Locations" > "Addresses" get me to nowhere around 0/0

**Comment by olivergrimm** [comment]
after consulting @3nids we will have a look onto this address location problems.

**Comment by skitourenguru** [comment]
I updated the Plugin and it works perfectly. Thanks a lot, its a great Plugin.
