### ISSUE TITLE
2 Feedbacks

### ISSUE THREAD

**Issue by ltbam** [opengisch/qgis-swiss-locator#23]
Very nice work and usefull plugin, congratulation!

1) I just could'nt add the "swissimage" layer, an error seems to occur.

2) Why use layers for WMS and not from WMTS, would'nt it be great to use swisstopo WMTS for rasters? 

Cheers
Rémy

**Comment by m-kuhn** [comment]
Thank you for the feedback.

1. Is this still an issue and if yes, could you provide us with details about the error?

2. This is currently being implemented, thanks to the qgis.ch user group.
