### ISSUE TITLE
resources_rc.py included twice in release zip

### ISSUE THREAD

**Issue by kannes** [opengisch/qgis-swiss-locator#36]
`swiss_locator/resources_rc.py` is included twice in the swiss_locator-1.4.6.zip archive for some reason

**Comment by kannes** [comment]
This might be a bug in https://github.com/opengisch/qgis-plugin-ci I guess? I found several other plugins with the same issue:

https://github.com/opengisch/qgis-swiss-locator/issues/36
https://github.com/dsgoficial/DSGToolsOp/issues/36
https://github.com/phborba/DeepLearningTools/issues/9
https://forge.chapril.org/linux_alpes/caliec/ (no issue filed because no account)
https://gitlab.com/Oslandia/qgis/qompligis (no issue filed because no account)

I filed a an issue at https://github.com/opengisch/qgis-plugin-ci/issues/111

**Comment by 3nids** [comment]
fixed in 1.4.8
