### ISSUE TITLE
Vector Tiles

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/qgis-swiss-locator#40]
It would be nice to be able to add vector tile layers too through the locator.

**Comment by 3nids** [comment]
see https://www.geo.admin.ch/fr/vector-tiles-service-services-et-donnees-disponibles

**Comment by 3nids** [comment]
https://api3.geo.admin.ch/services/sdiservices.html#mapbox-vector-tiles

**Comment by 3nids** [comment]
layers:
* basemap
* leichte-basiskarte
* leichte-basiskarte-imagery
* relief

**Comment by gacarrillor** [comment]
As for the relief layer, I still need to find the correct way of loading it. That is, a proper style (if any).
If we load it with no styles, we'd get different polygon colors each time:

![image](https://github.com/opengisch/qgis-swiss-locator/assets/652785/53e8bb1e-0914-4a1a-920f-72f5c2c95453)

![image](https://github.com/opengisch/qgis-swiss-locator/assets/652785/69e7fb48-52f4-4963-8ad4-75225d1a715e)

And this is the relief layer with each available style at https://api3.geo.admin.ch/services/sdiservices.html#getstyle with a map centered on Biel:

Relief layer with basemap style:
![image](https://github.com/opengisch/qgis-swiss-locator/assets/652785/f0b7c99e-612a-4bd2-b1bc-e9ebfa1a3fa7)


Relief layer with leichte-basiskarte style:
![image](https://github.com/opengisch/qgis-swiss-locator/assets/652785/40844b87-43bf-445f-895e-0bfc59988738)


Relief layer with leichte-basiskarte imagery style:
![image](https://github.com/opengisch/qgis-swiss-locator/assets/652785/1123d8db-72b1-4302-9bc6-ac28ef72459d)


Could we ask Swisstopo whether there is a recommended and published style for the Relief layer?
