### ISSUE TITLE
Closing info window crashes QGIS

### ISSUE THREAD

**Issue by mrtwister3142** [opengisch/qgis-swiss-locator#6]
Closing the info window crashes QGIS 3.8.0:
![infowindow](https://user-images.githubusercontent.com/32396976/60248894-de789580-98c3-11e9-95ef-a5b34b1bb2f1.png)

Crash ID: 6a074c491858b138cc4e1cb834ca89b91445862c

Stack Trace

QWindow::destroy :
QWindow::event :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processCloseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by 3nids** [comment]
could reproduce on Mac with Qt 5.12
cannot on linux with Qt 5.9

needs more investigation

**Comment by mrtwister3142** [comment]
Tried with a new profile, but the issue still persists (Windows 7).

Cannot reproduce on a different machine with QGIS 3.8.0 on Windows 10.

**Comment by m-kuhn** [comment]
@mrtwister3142 is this still an issue?

**Comment by mrtwister3142** [comment]
Not anymore after Upgrading to Windows 10.
