### ISSUE TITLE
Freeze on Windows

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/qgis-swiss-locator#8]
With QGIS 3.10.2, running some queries results in freeze/crash.
(1. search Bundeshaus, click on it, 2. search Arbon)

**Comment by olivierdalang** [comment]
@m-kuhn No freeze/crash here... but noticed a glitch with the popup the first time I clicked on a result (Bundeshaus) : the widget appeared very small (could only see title bar and close button), maybe it's linked ?

**Comment by m-kuhn** [comment]
Strange, we had that on two win 10 machines (and recently at another training I gave as well).
